"""updates

Revision ID: 0b276299a3d7
Revises: 1f6c8aaf56bd
Create Date: 2023-06-30 00:50:05.970201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b276299a3d7'
down_revision = '1f6c8aaf56bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'muscle_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.Text(),
               existing_comment='primary muscle involved',
               existing_nullable=False)
    op.alter_column('action', 'equipment',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.Text(),
               existing_comment='equipment used',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'equipment',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_comment='equipment used',
               existing_nullable=False)
    op.alter_column('action', 'muscle_type',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_comment='primary muscle involved',
               existing_nullable=False)
    # ### end Alembic commands ###
