"""change muscle_picture to plural

Revision ID: 1f6c8aaf56bd
Revises: 2ad9fa953ffc
Create Date: 2023-06-29 21:32:37.449689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f6c8aaf56bd'
down_revision = '2ad9fa953ffc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('muscle_pictures', sa.Text(), nullable=False, comment='muscle pictures'))
    op.drop_column('action', 'muscle_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('muscle_picture', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=False, comment='muscle picture'))
    op.drop_column('action', 'muscle_pictures')
    # ### end Alembic commands ###
