"""init tables

Revision ID: ab8852b316bf
Revises: 
Create Date: 2023-06-28 00:45:11.806753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8852b316bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='name'),
    sa.Column('source', sa.String(length=1024), nullable=False, comment='url'),
    sa.Column('source_hash', sa.String(length=32), nullable=False, comment='shorter url'),
    sa.Column('muscle_type', sa.String(length=64), nullable=False, comment='primary muscle involved'),
    sa.Column('other_muscle_type', sa.String(length=128), nullable=False, comment='other muscle involved'),
    sa.Column('difficulty_level', sa.String(length=32), nullable=False, comment='difficulty level'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='workout category'),
    sa.Column('equipment', sa.String(length=64), nullable=False, comment='equipment used'),
    sa.Column('cover', sa.Text(), nullable=False, comment='action cover'),
    sa.Column('action_pictures', sa.Text(), nullable=False, comment='action instruction pictures'),
    sa.Column('muscle_picture', sa.String(length=1024), nullable=False, comment='muscle picture'),
    sa.Column('instruction', sa.Text(), nullable=False, comment='action instructions'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='create time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_html',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('source', sa.String(length=1024), nullable=False, comment='source url'),
    sa.Column('source_hash', sa.String(length=32), nullable=False, comment='shorter url'),
    sa.Column('content', sa.Text(), nullable=False, comment='html'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='movie length(in seconds)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', name='uniq_idx_source_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_html')
    op.drop_table('action')
    # ### end Alembic commands ###
